name = "Grist Wonderland"
author = "Z4npher, ssamjh"
version = "1.3.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8747b08efec4c4f0729c97413a88c208face2bd17be9a0f606cb83cdb3c24297"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
