name = "Grist Wonderland"
author = "Z4npher, ssamjh"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dae0112b439123f699ac022a900a30c51fa40ddbec7779982f2c5af65177f0eb"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
