name = "Grist Wonderland"
author = "Z4npher, ssamjh"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dea9c7fe5a031d613c8b61a19eba6aed6d833da980acc8aa994c076a8d28473"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
