name = "Grist Wonderland"
author = "Z4npher, ssamjh"
version = "1.3.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "688dba94e9f8302f3e240e0dc6c64e51677582d428488293c489c849719b4e12"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
