name = "Grist Wonderland"
author = "Z4npher, ssamjh"
version = "1.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c022895d8849587b326a86312932e18be3572b22fc60456de03a35b066ac121d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
