name = "Grist Wonderland"
author = "Z4npher, ssamjh"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e091c80f9e2675cd9db19d2c67e440750829a97e229099f923266770da159ca"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
