name = "Grist Wonderland"
author = "Z4npher, ssamjh"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f43dbd4f7f49f0513d34eaf58f6ff584e6dc83d798d9e9944888a9d361571de"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
