name = "Grist Wonderland"
author = "Z4npher, ssamjh"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b3b263f9ee1ba564190a536f05f868e16e4d9ed665ce123ab3764b161ecc722"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
