name = "Grist Wonderland"
author = "Z4npher, ssamjh"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14b89241c7d2c11fe84e37346142e6f70b0ea241b5fe160bb1f3a7f02227f88d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
